### ISSUE TITLE
Any plans to add activate/deactivate functionality with cd?

### ISSUE THREAD

**Issue by 4l1fe** [glostis/venv-wrapper#3]
I didn't find a simple solution(zsh plugin) to activate `source .venv/bin/activate` an environment when i move to a project folder.
My preference is using the builtin `venv` module and don't have need to take something more complex.

**Comment by glostis** [comment]
Hi,

My workflow is generally to activate and deactivate my virtual environments by hand because I don't like them being tied to a single directory, so I haven't really thought about solutions to automatically activate an environment when entering a project folder.

It sounds like what you're looking for is what `dotpyenv` does: check out https://github.com/jeanpantoja/dotpyvenv

**Comment by 4l1fe** [comment]
Ok, i got you. Thx for the advice, `dotpyenv` seems to be what i look for.
